# Pandas Assignments
## Pandas

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [1]:
import pandas as pd
import numpy as np 

df = pd.DataFrame(np.random.randint(1,21,size = (4,6)))
print(df)

(df.set_index(0))

    0   1   2   3   4   5
0  15   5  19   6  20   1
1  14  15   1   4   9  10
2   5   7  18  17   8   4
3  13   1  15   2  11  14

     1   2   3   4   5
0
15   5  19   6  20   1
14  15   1   4   9  10
5    7  18  17   8   4
13   1  15   2  11  14

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [46]:
ind = ['X','Y','Z']
col = ['A','B','C']
df = pd.DataFrame(np.random.randint(1,21,size=(3,3)), columns=col , index= ind)
print(df)

print("\nElement is: ",df.at['Y','B'])

    A   B   C
X  17  20   4
Y   9   5  15
Z   5  11  11

Element is:  5

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [55]:
df = pd.DataFrame(np.random.randint(1,21,size=(5,3)))
display(df.head())
print(df.at[1,1])

    0   1   2
0   2  14  14
1   8  15  14
2  18   4   3
3  10   5  16
4  10  20  11

15

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [6]:
df = pd.DataFrame(np.random.randint(1,21,size=(4,3)))
display(df)

print("Row Sum:")
print(df.sum(axis = 1))
print("Column Sum: \n")
print(df.sum(axis = 0 ))

    0   1   2
0   3   2   6
1  10  14   9
2   2  14  19
3  19  18  18

Row Sum:
0    11
1    33
2    35
3    55
dtype: int64
Column Sum:

0    34
1    48
2    52
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [19]:
df = pd.DataFrame(np.random.randint(1,21,size=(5,3)))
indices = np.random.choice(15, size =3 , replace= False) 
rows , cols = np.unravel_index(indices= indices ,shape=(5,3))
for i,j in zip(rows, cols):
    df.iloc[i,j] = np.nan  
print("Array:")
display(df)
for i in df.columns:
    df[i] = df[i].fillna(df[i].mean())
print("\nFilled array:")
display(df)

Array:

      0   1     2
0   NaN  19  18.0
1   8.0  17  17.0
2   7.0   2   NaN
3   8.0   3   4.0
4  13.0  12   NaN

Filled array:

      0   1     2
0   9.0  19  18.0
1   8.0  17  17.0
2   7.0   2  13.0
3   8.0   3   4.0
4  13.0  12  13.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [24]:
df = pd.DataFrame(np.random.randint(1,31,size=(6,4)))
indices = np.random.choice(15, size =3 , replace= False) 
rows , cols = np.unravel_index(indices= indices ,shape=(5,3))
for i,j in zip(rows, cols):
    df.iloc[i,j] = np.nan 
print("Array:")
display(df)

df.dropna(inplace=True)
print("\nDropped array:")
display(df)

Array:

      0   1     2   3
0   8.0  28   NaN  14
1   NaN   8   NaN   1
2   5.0  29  20.0  13
3  18.0  30   6.0  21
4  25.0  26  29.0   5
5  14.0   2  28.0  28

Dropped array:

      0   1     2   3
2   5.0  29  20.0  13
3  18.0  30   6.0  21
4  25.0  26  29.0   5
5  14.0   2  28.0  28

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [25]:
col = ['Category', 'Value']
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'],size = 5),  'Value' : np.random.randint(1,21,size = 5)})
print("Data Frame:")
display(df)

df.groupby('Category')['Value'].agg(['sum','mean'])

Data Frame:

  Category  Value
0        B      7
1        A      9
2        B      5
3        C      6
4        C      9

          sum  mean
Category
A           9   9.0
B          12   6.0
C          15   7.5

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [27]:
df = pd.DataFrame({
    'Product': ["Laptop", "Mouse", "Shirt", "Jeans", "Apple",
                "Rice", "Phone", "T-Shirt", "Milk", "Headphones"],
    "Category": ["Electronics", "Electronics", "Clothing", "Clothing", "Grocery",
                 "Grocery", "Electronics", "Clothing", "Grocery", "Electronics"],
    "Sales": [45000, 1200, 1500, 2500, 200,
              800, 30000, 1000, 100, 2500]
})

display(df)

df.groupby('Category')['Sales'].sum()

      Product     Category  Sales
0      Laptop  Electronics  45000
1       Mouse  Electronics   1200
2       Shirt     Clothing   1500
3       Jeans     Clothing   2500
4       Apple      Grocery    200
5        Rice      Grocery    800
6       Phone  Electronics  30000
7     T-Shirt     Clothing   1000
8        Milk      Grocery    100
9  Headphones  Electronics   2500

Category
Clothing        5000
Electronics    78700
Grocery         1100
Name: Sales, dtype: int64

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [29]:
df1 = pd.DataFrame({
    'Product': ["Laptop", "Mouse", "Shirt", "Jeans", "Apple"],
    "Category": ["Electronics", "Electronics", "Clothing", "Clothing", "Grocery"]
})

df2 =df1 = pd.DataFrame({
    'Product': ["Laptop", "Mouse", "Shirt", "Jeans", "Milk"],
    "Sales": [45000, 1200, 1500, 2500, 100]
}) 

print("Data Frame 1:")
display(df1)
print("Data Frame 2:")
display(df2)

print("Merged DataFrame")
pd.merge(df1,df2, on='Product')

Data Frame 1:

  Product  Sales
0  Laptop  45000
1   Mouse   1200
2   Shirt   1500
3   Jeans   2500
4    Milk    100

Data Frame 2:

  Product  Sales
0  Laptop  45000
1   Mouse   1200
2   Shirt   1500
3   Jeans   2500
4    Milk    100

Merged DataFrame

  Product  Sales_x  Sales_y
0  Laptop    45000    45000
1   Mouse     1200     1200
2   Shirt     1500     1500
3   Jeans     2500     2500
4    Milk      100      100

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [33]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [23, 25, 22]
})
df2 = pd.DataFrame({
    "City": ["New York", "London", "Tokyo"],
    "Salary": [50000, 60000, 55000]
})
print("Data Frame 1:")
display(df1)
print("Data Frame 2:")
display(df2)

df_row = pd.concat([df1, df2], axis=0)
print("Row Concat")
display(df_row)

df_col = pd.concat([df1, df2], axis=1)
print("Column Concat")
display(df_col)

Data Frame 1:

      Name  Age
0    Alice   23
1      Bob   25
2  Charlie   22

Data Frame 2:

       City  Salary
0  New York   50000
1    London   60000
2     Tokyo   55000

Row Concat

      Name   Age      City   Salary
0    Alice  23.0       NaN      NaN
1      Bob  25.0       NaN      NaN
2  Charlie  22.0       NaN      NaN
0      NaN   NaN  New York  50000.0
1      NaN   NaN    London  60000.0
2      NaN   NaN     Tokyo  55000.0

Column Concat

      Name  Age      City  Salary
0    Alice   23  New York   50000
1      Bob   25    London   60000
2  Charlie   22     Tokyo   55000

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [43]:
df = pd.DataFrame({
    'Value': np.random.randint(1, 101, size=10)
},index = pd.to_datetime([
    "2025-01-05",
    "2025-01-12",
    "2025-01-20",
    "2025-02-03",
    "2025-02-18",
    "2025-03-01",
    "2025-03-15",
    "2025-03-25",
    "2025-04-10",
    "2025-04-22"
]))

print("Data Frame:")
display(df)

df.resample('ME').mean()

Data Frame:

            Value
2025-01-05     16
2025-01-12     44
2025-01-20     53
2025-02-03     20
2025-02-18     65
2025-03-01     27
2025-03-15     31
2025-03-25     62
2025-04-10     75
2025-04-22     12

                Value
2025-01-31  37.666667
2025-02-28  42.500000
2025-03-31  40.000000
2025-04-30  43.500000

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [48]:
r = pd.date_range('2021-01-01','2021-12-31', freq='D')
df = pd.DataFrame(r, columns=['Date'])
df['Value'] = np.random.randint(0,100,size = (len(r)))
df.set_index('Date',inplace=True)
print("Data Frame")
display(df)

roll = df.rolling(window=7).mean()
print("Rolling mean Data Frame")
display(roll.head(10))

Data Frame

            Value
Date
2021-01-01      6
2021-01-02     38
2021-01-03     76
2021-01-04     60
2021-01-05     52
...           ...
2021-12-27     69
2021-12-28     92
2021-12-29     26
2021-12-30     52
2021-12-31     77

[365 rows x 1 columns]

Rolling mean Data Frame

                Value
Date
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
2021-01-06        NaN
2021-01-07  38.428571
2021-01-08  44.428571
2021-01-09  49.142857
2021-01-10  42.714286

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [5]:
arr = [['A','A','B','B'],[1,2,1,2]]
indices = pd.MultiIndex.from_arrays(arr, names=['Main', 'Sub'] )
df = pd.DataFrame(np.random.randint(1,21,size=(4,4)), index= indices ,columns= ['V1','V2','V3','V4'])
print("Data Frame:")
display(df)

print("\nIn Main Category A")
print(df.loc['A'])

print("\nIn the main with sub group")
print(df.loc['B',2])

Data Frame:

          V1  V2  V3  V4
Main Sub
A    1    16  15  20   6
     2     6  13  18   3
B    1    19  15  13   8
     2     4   2   3  12

In Main Category A
     V1  V2  V3  V4
Sub
1    16  15  20   6
2     6  13  18   3

In the main with sub group
V1     4
V2     2
V3     3
V4    12
Name: (B, 2), dtype: int32

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [26]:
index = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size=20) ,'SubCategory': np.random.choice([1,2], size=20)})
indices = pd.MultiIndex.from_frame(index)
df = pd.DataFrame(np.random.randint(1,21,size=(20,4)), index= indices ,columns= ['V1','V2','V3','V4'])
print("Data Frame:")
df = df.sort_index(level=['Category','SubCategory'])
display(df)
print()
df.groupby(['Category','SubCategory']).sum()

Data Frame:

                      V1  V2  V3  V4
Category SubCategory
A        1            18   2  13  17
         1             4   2  12  10
         1             3  17   2  20
         1            16  10   3   3
         1            19   7   9   8
         2             3  14   6   6
B        1             9  13  10   3
         1            15   4  14   8
         1             3   9   6   6
         1             9   9  19  11
         2            10   8  19   4
         2             6   4  19  12
C        1            10   4   2   9
         1             1  19   2  17
         1             5   1   5   9
         1            11   8  13  14
         1            15  19  18   5
         2            13  15  17   5
         2             8   1  20   9
         2            20  20  19   9

                      V1  V2  V3  V4
Category SubCategory
A        1            60  38  39  58
         2             3  14   6   6
B        1            36  35  49  28
         2            16  12  38  16
C        1            42  51  40  54
         2            41  36  56  23

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [28]:
df = pd.DataFrame({
    'Date' : np.random.choice(
        pd.date_range('2024-01-01', '2024-12-31'),size= 10
    ),
    'Category': np.random.choice(['A','B','C'],size=10),
    'Value': np.random.randint(1,100,size = 10)
})

print("Data Frame:")
display(df)

df.groupby(['Category','Date'])['Value'].sum()

Data Frame:

        Date Category  Value
0 2024-12-28        C      2
1 2024-09-23        B     54
2 2024-01-31        A     37
3 2024-04-03        A     56
4 2024-05-25        A     29
5 2024-03-26        C     46
6 2024-06-03        A     48
7 2024-12-24        A     95
8 2024-07-24        C     99
9 2024-07-04        A     22

Category  Date
A         2024-01-31    37
          2024-04-03    56
          2024-05-25    29
          2024-06-03    48
          2024-07-04    22
          2024-12-24    95
B         2024-09-23    54
C         2024-03-26    46
          2024-07-24    99
          2024-12-28     2
Name: Value, dtype: int32

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [32]:
df = pd.DataFrame({
    'Year': np.random.choice([2022, 2023, 2024], size=10),
    'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=10),
    'Revenue': np.random.randint(1000, 10000, size=10)
})

print("Data Frame:")
display(df)

display(df.groupby(['Year', 'Quarter'])['Revenue'].sum())

Data Frame:

   Year Quarter  Revenue
0  2023      Q3     7221
1  2022      Q3     2831
2  2024      Q3     9374
3  2024      Q2     7995
4  2024      Q2     1320
5  2023      Q4     4817
6  2024      Q4     5271
7  2023      Q3     6401
8  2024      Q2     1190
9  2022      Q2     7363

Year  Quarter
2022  Q2          7363
      Q3          2831
2023  Q3         13622
      Q4          4817
2024  Q2         10505
      Q3          9374
      Q4          5271
Name: Revenue, dtype: int32

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [35]:
df = pd.DataFrame(np.random.randint(1,100,size=(5,3)), columns=['Value1','Value2','Value3'])

print("Data Frame:")
display(df)

print("\nAfte doubling")
df =df*2
display(df)

Data Frame:

   Value1  Value2  Value3
0      48      15      36
1      69      62      84
2      10      48      54
3      77      21      65
4       1      23       1

Afte doubling

   Value1  Value2  Value3
0      96      30      72
1     138     124     168
2      20      96     108
3     154      42     130
4       2      46       2

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [38]:
df = pd.DataFrame(np.random.randint(1,100,size=(6,3)), columns=['Value1','Value2','Value3'])
print("Data Frame:")
display(df)

print("After Applying Function")
df.apply(lambda x:x.sum(), axis= 1)

Data Frame:

   Value1  Value2  Value3
0      42      26      10
1      29      61      32
2      66      54      35
3      87      11      77
4      54       7      86
5       5      63      46

After Applying Function

0     78
1    122
2    155
3    175
4    147
5    114
dtype: int64

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [45]:
txt = ['Apple','Ball','Cat','Dog','Egg']
df = pd.Series(txt)
print("Data Frame:")
display(df)

upper = df.str.upper()
print("\nUpper case Data Frame")
display(upper)

Data Frame:

0    Apple
1     Ball
2      Cat
3      Dog
4      Egg
dtype: str

Upper case Data Frame

0    APPLE
1     BALL
2      CAT
3      DOG
4      EGG
dtype: str

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [48]:
txt = ['Apple','Ball','Cat','Dog','Egg']
df = pd.Series(txt)
print("Data Frame:")
display(df)

df.apply(lambda x: x[:3])

Data Frame:

0    Apple
1     Ball
2      Cat
3      Dog
4      Egg
dtype: str

0    App
1    Bal
2    Cat
3    Dog
4    Egg
dtype: str